env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - prettier
parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
  sourceType: module
plugins:
  - my-rules
rules:
  my-rules/import-alphabetic-order: error
  '@typescript-eslint/no-non-null-assertion': warn
overrides:
  - files: ['src/**/*.spec.ts']
    extends:
      - plugin:mocha/recommended
    plugins:
      - mocha
